import json,glob,os
S=os.environ.get('WORK', '.') # folder with lv2/, spall/ (and lib_analysis.csv)
REPO=os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', '..')
DRAW_CLASSES=(2,3,5,9,10,15)
def uid(k):
    c,m,dr=map(int,k.split(','))
    return (c,m,1 if dr==1 and c in DRAW_CLASSES else 2)
levels={}
for f in glob.glob(S+'/lv2/*.json'):
    d=json.load(open(f)); u={}
    for k,v in d['max'].items():
        if v<=0: continue
        key=uid(k); u[key]=max(u.get(key,0),v)
    levels[d['level']]=(u,sorted(d['spells']))
spells={}
for sp in range(26):
    u={}
    for lv in range(3):
        f=f'{S}/spall/{sp}_{lv}.json'
        if not os.path.exists(f): continue
        d=json.load(open(f))
        for k,v in d['max'].items():
            dlt=v-d['first'].get(k,0)
            if dlt<=0: continue
            c=int(k.split(',')[0])
            # only what the spell itself makes: effects (9, 10); creatures only for Summon Army
            if c in (9,10) or (c==5 and sp==19):
                key=uid(k); u[key]=max(u.get(key,0),dlt)
    spells[sp]=u
def fmt(u):
    return '{'+', '.join(f'Vector3i({a},{b},{c}): {n}' for (a,b,c),n in sorted(u.items()))+'}'
out=['# Generated by an analysis run of the engine (every level for 3000 steps, every spell at',
'# levels I-III): how many entities of each kind (Vector3i(class, model, libType)) were drawn at',
'# the same time. Used to fill the entity pool before they are needed. Do not edit by hand.',
'','# level -> {uid: max count at the same time}','const LEVELS = {']
for lv in sorted(levels): out.append(f'\t{lv}: {fmt(levels[lv][0])},')
out+=['}','','# level -> spells seen in it (the ones the wizards have and the ones placed in the level)','const LEVEL_SPELLS = {']
for lv in sorted(levels): out.append(f'\t{lv}: {levels[lv][1]},')
out+=['}','','# spell index -> {uid: max count one cast of it makes at the same time}','const SPELLS = {']
for sp in range(26): out.append(f'\t{sp}: {fmt(spells[sp])},')
out+=['}','']
open(os.path.join(REPO, 'godot-code/scenes/entity_prefill_data.gd'),'w').write('\n'.join(out))
print(len(levels), sum(len(v[0]) for v in levels.values()), {k:sum(v.values()) for k,v in spells.items()})
