; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Magic Balls"
#define MyAppEditorName "Magic Editor"
#define MyAppVersion "0.0.0.0"
#define MyAppPublisher "@turican"
#define MyAppURL "https://github.com/turican0/MagicBalls/"
#define MyAppExeName "MagicBalls.exe"
#define MyAppEditorExeName "editor.bat"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A5EFFFED-C9FA-4BE1-8982-6F4559672B4D}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=MagicBallsSetup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
DefaultGroupName=Magic Balls
ArchitecturesInstallIn64BitMode=win64
UninstallDisplayIcon={app}\app.ico

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[CustomMessages]
DeleteDataQuery=Do you want to delete all user settings and application data (save files) for Magic Balls?

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\godot-code\MBEXout\bin\windows\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\exports\release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\scripts\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "app.ico"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "editor.ico"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\app.ico"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; IconFilename: "{app}\app.ico"
Name: "{group}\{#MyAppEditorName}"; Filename: "{app}\{#MyAppEditorExeName}"; IconFilename: "{app}\editor.ico"
Name: "{autodesktop}\{#MyAppEditorName}"; Filename: "{app}\{#MyAppEditorExeName}"; Tasks: desktopicon; IconFilename: "{app}\editor.ico"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  UserDataPath: string;
begin
  if CurUninstallStep = usUninstall then
  begin
    // Adjusted specifically for Godot's folder structure
    UserDataPath := ExpandConstant('{userappdata}\Godot\app_userdata\{#MyAppName}');

    if DirExists(UserDataPath) then
    begin
      if MsgBox(CustomMessage('DeleteDataQuery'), mbConfirmation, MB_YESNO) = IDYES then
      begin
        // Recursively deletes the Godot app_userdata folder for this game
        DelTree(UserDataPath, True, True, True);
      end;
    end;
  end;
end;